lane :test do
  expiry_date = certificate_expirydate({
    certificate_filepath: "certs/test_certificate.p12",
    certificate_password: "test password"
  })

  elapsed_time = DateTime.now - expiry_date

  if elapsed_time > 0
    UI.error!(
      "The certificate, \"certs/test_certificate.p12\", expired " \
      "on #{expiry_date.strftime('%FT%R')}"
    )
  end
end
